version: "3"

services:
  databse:
    image: mongo:4.4.1-bionic
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=iotdatabase
      - MONGO_INITDB_ROOT_USERNAME=iot
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    ports:
      - 27017:27017
volumes:
  mongodb:
  mongoconfig: